name: Markdown Linter

on:
  pull_request:
    branches: [main]
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Run Markdown Lint
        run: make lint